### ISSUE TITLE
Cannot import parameters from an oprah exports file

### ISSUE THREAD

**Issue by tnation14** [ACloudGuru/oprah#156]
# This is a Bug Report

## Description
I can't import parameters from an oprah exports file.

```bash
# yarn oprah export -s acg                                                     
Oprah: Stage  --> acg
Oprah: Config --> /Users/taylor/Documents/projects/src/acloudguru/cloud-optimization/aws/cost-and-usage/oprah.yml
Oprah: Getting parameters..
Oprah: Saving parameters to: /tmp/oprah-exports.json
Oprah: Done.
✨  Done in 1.02s.

# yarn oprah import -s acg
Oprah: Stage  --> acg
Oprah: Config --> /Users/taylor/Documents/projects/src/acloudguru/cloud-optimization/aws/cost-and-usage/oprah.yml
Oprah: Getting parameters from: /tmp/oprah-exports.json
Oprah: Updating config...
Oprah: ERROR: TypeError: Reduce of empty array with no initial value
```

For bug reports:
* What went wrong? I was unable to import parameters from a file generated by `oprah export`
* What did you expect should have happened? I should be able to run `oprah export`, then run `oprah import` using the same file.
* What was the config you used?
```yaml
service: optimization-service
provider:
  name: ssm

config:
  path: /${stage}/optimization/config

  defaults:
    NOTIFICATION_EMAIL: dev-accounts@acloud.guru
    SLACK_WORKSPACE_ID: <REDACTED> # PineHeadGurus
    SLACK_CHANNEL_ID: <REDACTED> # wg-cost-control

  test:
    INCLUDE_RESOURCE_IDS: true

  acg:
    ORGANISATION_NAME: acloudguru
    INCLUDE_RESOURCE_IDS: true
    DAILY_BUDGET_USD: <REDACTED>
    MONTHLY_BUDGET_USD: <REDACTED>

  laasprod:
    ORGANISATION_NAME: laasprod
    INCLUDE_RESOURCE_IDS: false
    DAILY_BUDGET_USD: <REDACTED>
    MONTHLY_BUDGET_USD: <REDACTED>
```
* What stacktrace or error message from your provider did you see? `ERROR: TypeError: Reduce of empty array with no initial value`

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Stack Trace***:
* ***Provider Error messages***:
